input {
	file {
		path => "/csv/cities.csv"
		start_position => end
	}
}
filter {
	csv {
		columns => ["country","city","accentCity","region","population"]
	}		
	mutate {
		add_field => {
			"location" => "%{column6},%{column7}"
		} 
		remove_field => [ "message", "@version","@timestamp","host","path","column6","column7" ]	
	}
}
output {
	stdout { codec => rubydebug }
	elasticsearch {
		index => "cities"
		hosts => "elasticsearch:9200"
		user => "elastic"
		password => "changeme"
		ecs_compatibility => disabled
	}
}
